### ISSUE TITLE
Feature request: KHR_mesh_quantization

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_gltf_renderer#10]
is it possible to support KHR_mesh_quantization?

**Comment by mklefrancois** [comment]
We do not plan to support this extension in the near future. In the meantime, if data compression is important, the `nvvkhl::SceneVk::createVertexBuffers` function can be overloaded to upload the vertex data. Then the `vertex_accessor.h` must be synchronized with this new data.
