### ISSUE TITLE
use only pre-compiled shaders

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_gltf_renderer#11]
is it possible to make build for not use dlls of shader compilers?
maybe flag in cmake?
for use only one exe without need additional dlls

**Comment by mklefrancois** [comment]
It should already be the case. The compilers are using DELAYLOAD, as shown below.

```
    target_link_options(${PROJNAME} PRIVATE "/DELAYLOAD:shaderc_shared.dll")
    target_link_options(${PROJNAME} PRIVATE "/DELAYLOAD:slang.dll") 
```

In runtime, there is a test to see if those are available, but they are not needed for the application to run. The CMake will copy the DLL by default, but they can be removed. 

Let me know if you encounter any issues.

**Comment by mklefrancois** [comment]
If the DLLs can't be found, the functionality and menu to reload the shaders shouldn't be present. Remove the DLLs next to the executable, make sure the path to the Vulkan SDK isn't reachable (this is added by default during installation), then the menu should not show up and neither the ability to reload shaders.
