### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by apchenstu** [nvpro-samples/vk_gltf_renderer#14]
Thank you for creating this great repo! Do you have any plans to make it support morph targets and skins soon?

**Comment by mklefrancois** [comment]
Hi @apchenstu, thank you for the kind words. There is a plan to support all animations, but it's not possible to give any estimate at this time.

**Comment by mklefrancois** [comment]
Hi, animation is coming. There is already node animation, but morph and skin will be implemented as well.
