### ISSUE TITLE
idea for emissives

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_gltf_renderer#17]
is I think correct if pbrMat.emissive > vec3(0.0f) then we can not to sample or eval other parts of material parameters?
and after of 
https://github.com/nvpro-samples/vk_gltf_renderer/blob/96492c57fbb83cc0f7f7ad992ce88a9de5c9d772/shaders/rt_common.h#L224

can be added check for pbrMat.emissive > vec3(0.0f) with return?

**Comment by mklefrancois** [comment]
Further calculations are required because the emissive material may also be diffuse or reflective. We can think of a very dim light bulb in a very bright environment.
