### ISSUE TITLE
Alpha channel is not set as zero in pathtrace.comp.glsl

### ISSUE THREAD

**Issue by PROLCY** [nvpro-samples/vk_gltf_renderer#18]
Thanks for your hard work!

I use the indirect path tracing in my code. 
I set the alpha channel in pathtrace.comp.glsl as 0 as follows:
```
// imageStore(image, ivec2(samplePos.xy), vec4(mix(old_color, pixel_color, a), 1.0F));

imageStore(image, ivec2(samplePos.xy), vec4(mix(old_color, pixel_color, a), 0.0F));
```

But the final saved image in png format has alpha value as 255 in all pixels.
How can I apply it?

**Comment by mklefrancois** [comment]
Thanks for the kind words.

The reason is that the tonemapper sets the alpha to 1.0 and it is the tonemapped image that is saved. 
There is a local version that sets the alpha==0 for the background. Is this the effect you wanted to achieve?

See: https://github.com/nvpro-samples/nvpro_core/blob/master/nvvkhl/shaders/tonemapper.comp.glsl#L52

**Comment by PROLCY** [comment]
Thanks a lot! I got it!

I am implementing the function like shadow catcher in Blender. 
I added two mesh (an example mesh and a plane) into gltf scene and rendered it using path tracing. 
I want to extract only an example mesh and shadow on plane in final saved image, so I will set the alpha channel as zero in hdr dome and plane except for shadow region. 

May I get your advice or tip about this process? I got some noise and unsatisfied result.

**Comment by mklefrancois** [comment]
There is an update for both nvpro-core and gltf_renderer which now correctly sets the background alpha to 0.
![flight-helmet](https://github.com/user-attachments/assets/fec40853-a0f7-4a47-8f62-ef834b2fc8fa)

If you are trying to implement a shadowcatcher on a plane, you should try to add a virtual plane (P, N). Then check in the function `pathTrace()` if the ray hits nothing on the first ray. If this is the case, and your virtual shadow plane catcher is active, check if the hit would be under shadow with the virtual plane. 

You can call `bool inShadow = traceShadow(shadowRay, lightDist, seed);` to do this. Besides calculating the intersection point with the virtual plane, you also need the direction to a light. This information is usually called later, but it is possible to get it with `sampleLights()`. 

It would be interesting to see if you can get it to work. Please post pictures of your results.

**Comment by PROLCY** [comment]
Thank you for detailed explaination!

I applied a little bit different approach and got some nice results. 

![sample](https://github.com/user-attachments/assets/625d2af9-c5da-4b19-aa2d-b6ea801dd277)

I add the plane mesh into my gltf scene and filter it out when rendering. 
I record the first hit node when depth is 0 and use it for setting alpha channel.

If first hit node is not my object, alpha channel should be 0. 
But when it is plane and in shadow (use ```inShadow```), alpha cannel is set as non-zero value (i.e. 0.8).
I found that the shadow color is mixed with plane color, so I convert it to gray scale. 

This is my approach to catch shadow. 
If you have a comment for this, I will try to apply it for improving.

**Comment by mklefrancois** [comment]
Thanks for providing images of your work. Your idea works, but it's limited in flexibility, and like you wrote, it captures the color of the plane and not only the shadow that would be projected on it. This would make it hard to blend on a different surface. I think a shadow catcher plane is a better technique for what you're trying to achieve.

Note that the sample has been updated and now also has the ability to have a solid color background. This helps blending objects, as the alpha on the edges aren't combining with the HDR or sky environment, giving better results
