### ISSUE TITLE
base color texture opacity doesnt works

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_gltf_renderer#21]
I tested [this scene](https://drive.google.com/file/d/1JQeA8iHVeZPp_snRQZqhzxnBxvLSAZov/view?usp=sharing) and one texture contains opacity but rendered like no opacity.
I use many opacity option changes but has no effect.
Take look at white leaves
![p1-environment-light](https://github.com/user-attachments/assets/90e49ed6-9811-464b-879f-922eb596a24b)

How to solve it?

**Comment by tigrazone** [comment]
reuploaded. use same url

**Comment by mklefrancois** [comment]
The blending for the leaves should be set to MASK.

The next update should allow to change those flags interactively. 

![image](https://github.com/user-attachments/assets/9b291aff-5544-4f92-adca-d41c6b6a644b)

Before
![image](https://github.com/user-attachments/assets/5334fbd1-36f2-47c2-8e55-7d05462a07fe)
After
![image](https://github.com/user-attachments/assets/1d26409b-7a30-49bd-8b1e-81fc8a1b39c1)

**Comment by mklefrancois** [comment]
There was an update for both [vk_gltf_renderer](https://github.com/nvpro-samples/vk_gltf_renderer) and [nvpro_core](https://github.com/nvpro-samples/nvpro_core).
Hopefully this will also fix some transparency issues with thin-walled elements.

**Comment by tigrazone** [comment]
thanks! works fine
