### ISSUE TITLE
Questions about tangents

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_gltf_renderer#23]
Hello.
I'm read sources of work with tangent code closely and I have not understand some lines
1. 
https://github.com/nvpro-samples/vk_gltf_renderer/blob/5a02beb1e28d05d652201a1c47409f4f5168745f/shaders/get_hit.h#L82
What do this line and why it needed?
2. Why need to switch signs for three components?
When I try to use this code with dielectrics with new project - just use stored normals and tangents data  - this code gives wrong result - normals switched to wrong side and after commenting it all is started to be ok
https://github.com/nvpro-samples/vk_gltf_renderer/blob/5a02beb1e28d05d652201a1c47409f4f5168745f/shaders/get_hit.h#L92-L97
3. When normal mapping is processed I see some strange piece of code
https://github.com/nvpro-samples/nvpro_core/blob/d5ec94434ccbee3f480d741ee80fa2ba7522dd44/nvvkhl/shaders/pbr_mat_eval.h#L144-L148
Why normalize used twice for T and B?
It was normalized before in get_hit.h
Is it needed to recalculate only for normal mapping code? Why this code not in the condition where normal is changed by normal mapping?
4. Next piece of code where tangents is changed is Anisotropy code
https://github.com/nvpro-samples/nvpro_core/blob/d5ec94434ccbee3f480d741ee80fa2ba7522dd44/nvvkhl/shaders/pbr_mat_eval.h#L264-L265

About 3 and 4. 
Why not to use same code for this 2 cases?
Is it all these calculations can be simplified and maybe use it only if needed? This calculations can be a speed bottleneck for path tracer because it used for every bounce, needed this data or not needed

**Comment by mklefrancois** [comment]
Hi @tigrazone , 

1. This is to ensure that the tangent is orthogonal.
2. If the tangent and bitangent aren't inverted, they may no longer be orthogonal to the normal.
3. You are right, there seems to be unnecessary calculation here.
4. And for this, we could merge with some refactoring of 3.

Thanks, we'll look into it.

**Comment by tigrazone** [comment]
2. Why this inversion makes dielectrics procession wrong?
Without usage of tangent code it was works ok

**Comment by tigrazone** [comment]
5. Which of tangent calculation functions is do max precision result?
nvh::GltfScene::createTangents() or makeFastTangent()?
I dont ask about mikktspace variant

**Comment by tigrazone** [comment]
> 2. Why this inversion makes dielectrics procession wrong?
>    Without usage of tangent code it was works ok

Maybe needed some double-sided processing?
I seen changes on commits

**Comment by tigrazone** [comment]
> (2) Can you provide details regarding this item?
> It would be nice to have images and the scene to investigate.

It is not possible because I use just tangent usage code in shader and whole program not use nvpro_core
