### ISSUE TITLE
program fails after load BistroExterior scene on last commit

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_gltf_renderer#24]
[scene](https://drive.google.com/file/d/1g58-OA9TkTgkGd6lO4H4PeqmJcxUUuuz/view?usp=sharing)
prev commit of nvpro_core and vk_gltf_renderer loads this scene w/o errors and program fail.
I try to build with aftermath but it doesnt helps - program fails before aftermath can do dump

**Comment by tigrazone** [comment]
I use 3060 and windows 10. 
tomorrow I do reproduce and post screenshots

**Comment by tigrazone** [comment]
new commit fix error.
maybe it was side effects of tangent calculation and multithreading.
and now this scene renders faster.
was 11 fps. now 28 fps

**Comment by mklefrancois** [comment]
Great, thanks for the confirmation. I also tested on our local branch, which is why I didn't see the problem.
