### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/vk_gltf_renderer#8]
![зображення](https://github.com/user-attachments/assets/78fd82e2-88c0-435a-b346-fb0985790cb9)
![зображення](https://github.com/user-attachments/assets/df49d681-2b7e-4d88-afee-3ec6b8a61e0c)
test scenes taken from default gltf 2.0 sample models.
This issue with loaded HDRI. Without HDRI - with sun&sky - there is no issue

**Comment by mklefrancois** [comment]
Thanks for reporting, this is due to an error we have recently made in the calculation of MIS weight when hitting the environment. 
Working on a proper fix.
